language: ruby
rvm:
- 2.5.3

branches:
  only:
    - master

deploy:
  provider: heroku
  api_key:
    secure: aFbuEi+kbnjWZ0+K4D8aWPlD6uH3CJCT6k4ciCWHshinalSy6hYNzd3tf96L4WIe48Qt51ti/ECiWIffuBwREwXxJIcJAB4P/mQCzz3Q+MWknVLpm2pFpoxp6DX2LethjcvX9otAC7TzVW9bQCFAFVNt+qNMA+jhiwlj5Onq6QYXwk+XRr5rTfh3pk5F5w3qAy3VNQeyb7nZZGN9JFXjcpGezrqqATXv5hFUTRiAxalKgPqxuDzq9AFdSmMYR0h81lXRzqXJQ/ezFeiON0SkpVkiAUOsSGMigH2jWWPp6gWkxZ1z7RsqrGW6ULu1u2sncd2X6BpgGv+bKCEg0F5GIIZnwqWHUXk0WGoMD1PRMxBjMhhOoHQhS4Jnod8Qix9P+NFfhPGkzBXrU/vEOivrb6wOQT8xptTTuA8jntzvQlKR3GGAUHM22O/mmIjpE0ENRu9fy8OPbcawIjZeLRpW6vrYnqjubMkUYw8pNE/lQpUKegoEqnqb3PC8k231JUz4/kni1OJHV4yhd3K0wqZJcmbzwf+UwKIbJzT5p+yxJpBYSGhLnMh8aNqE9i0jlY8mKIwcJcRiW24cpcnqrsc7Nvi25vleKoN3mxtvsfSnAVvkssK7OFT/efaEPCISnUgqZJR53ELm2QdkTQmLtX4IP3xDktlSL3xGZP7gXcP3Uog=
  app: comp-matrix
  run:
    - 'bundle exec rake db:migrate'

